//REQUIRE EXPRESS

//CREATE INSTANCE OF EXPRESS

//CREATE PORT FOR THE APP TO RUN
//BUT ALSO LISTEN TO ENVIRONMENT VARIABLES SO WE CAN DEPLOY TO HEROKU

//ADD MIDDLEWARE
//COPY/PASTE FROM STAR WARS APP

//CREATE AN ARRAY OF TABLES
//CREAT AN ARRAY FOR WAITLIST

//ARRAY OF OBJECTS. OBJECTS SHOULD HAVE
//NAME
//PHONE
//EMAIL
//ID

//HTML ROUTES
//ROUTE FOR HOME
//ROUTE FOR TABLES
//ROUTES FOR RESERVE

//API ROUTES
//GET ALL TABLE DATA
//CREATE TABLE/RESERVATION

//LISTEN ON THE PORT

